---
#############################################################
# Create Device Roles in Nautobot
############################################################# 
- name: Create device role within Nautobot
  networktocode.nautobot.device_role:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: no
    name: "{{ item.1.name }}"
    color: "{{ item.1.color }}"
    state: present
  loop: "{{ manufacturer | subelements('device_roles', 'skip_missing=True') }}"