---
configuration:
  interfaces:
    l3_interfaces:
      - name: GigabitEthernet0/0
        description: "UPLINK TO INTERNET PROVIDER"
        ipv4: 24.24.3.2
        ipv4_mask: 255.255.255.0

      - name: GigabitEthernet0/1
        description: "DOWNLINK POD1SW1"
        ipv4: 10.30.1.0
        ipv4_mask: 255.255.255.254
        ospf:
          area: 0
          network: "point-to-point"

      - name: GigabitEthernet0/2
        description: "DOWNLINK POD1SW2"
        ipv4: 10.30.1.2
        ipv4_mask: 255.255.255.254
        ospf:
          area: 0
          network: "point-to-point"        

      - name: Loopback0
        description: "iBGP LOOPBACK"
        ipv4: 10.3.1.1
        ipv4_mask: 255.255.255.255
        ospf:
          area: 0
          network: "point-to-point"


