---
configuration:
  bgp:
    ibgp:
      l_asn: 65001
      neighbors:
        - 10.0.1.1
        - 10.0.1.2
    address_family_ipv4:
      advertised_networks:
        155.1.1.0: {net_mask: 255.255.255.192 }
        155.1.1.64: {net_mask: 255.255.255.192 }
        155.1.1.128: {net_mask: 255.255.255.192 }    

