---
configuration:
  interfaces:
    l3_interfaces:
      - name: vlan300
        description: "USER_SVI"
        ipv4: 155.3.1.3
        ipv4_mask: 255.255.255.192
        dhcp_helper: 10.3.1.1
        vrrp_group: 1
        vrrp_description: USER_VLAN
        vrrp_priority: 100
        vrrp_primary_ip: 155.3.1.1

      - name: vlan350
        description: "SERVER_SVI"
        ipv4: 155.3.1.67
        ipv4_mask: 255.255.255.192
        dhcp_helper: 10.3.1.1
        vrrp_group: 2
        vrrp_description: USER_VLAN
        vrrp_priority: 100
        vrrp_primary_ip: 155.3.1.65

      - name: vlan400
        description: "GUEST_SVI"
        ipv4: 155.3.1.131
        ipv4_mask: 255.255.255.192
        dhcp_helper: 10.3.1.1
        vrrp_group: 3
        vrrp_description: USER_VLAN
        vrrp_priority: 100
        vrrp_primary_ip: 155.3.1.129

      - name: GigabitEthernet0/0
        description: "UPLINK POD1R1"
        ipv4: 10.30.1.3
        ipv4_mask: 255.255.255.254
        ospf:
          area: 0
          network: "point-to-point"

      - name: Loopback0
        description: "iBGP LOOPBACK"
        ipv4: 10.3.1.3
        ipv4_mask: 255.255.255.255
        ospf:
          area: 0
          network: "point-to-point"


