---
configuration:
  dhcp_pool:
    - name: 300
      network: "155.5.1.0 /26"
      default_router: .1.1
      lease: 30
      excluded_address: "155.5.1.1 155.5.1.3"

    - name: 350
      network: "155.5.1.64 /26"
      default_router: 155.5.1.65
      lease: 30
      excluded_address: "155.5.1.65 155.5.1.67"

    - name: 400
      network: "155.5.1.128 /26"
      default_router: 155.5.1.129
      lease: 30
      excluded_address: "155.5.1.129 155.5.1.131"